SELECT
CASE 
    WHEN COUNT(vp.DETR_EFFECT_NAME) > 0 THEN 
      'Действующие вредные привычки: ' || 
      LISTAGG(vp.DETR_EFFECT_NAME, '; ') WITHIN GROUP (ORDER BY vp.DETR_EFFECT_NAME)
    ELSE NULL
END AS VRED
FROM D_V_AGENT_DETR_EFFECTS vp
JOIN D_V_AGENTS a ON a.id = vp.PID
JOIN D_V_DETRIMENTAL_EFFECTS d ON d.ID = vp.DETR_EFFECT
JOIN D_V_PERSMEDCARD pmc ON pmc.AGENT = a.ID
JOIN D_V_DIRECTION_SERVICES ds ON ds.PATIENT = pmc.ID
WHERE 1=1
AND vp.IS_ACTUAL = '1'
AND ds.ID = :DIRECTION_SERVICE
