SELECT
qq.QQ_NAME AS QUEST,
qa.ANSWER AS ANS,
qa.ANS_VALUE AS BALL,
aq.DATE_CREATE
FROM D_VISITS v
JOIN D_AGENT_QUESTIONARIES aq ON aq.UNIT_ID = v.ID
JOIN D_AGENT_QUEST_ANSWERS aqa on aq.id=aqa.pid
JOIN D_QUEST_QUESTIONS qq ON qq.id = aqa.QUESTION
JOIN D_QUEST_ANSWERS qa ON qa.id = aqa.ANSWER
JOIN D_QUESTIONARIES q ON q.id = aq.QUESTIONARY
JOIN D_DIRECTION_SERVICES ds ON ds.ID = v.PID
WHERE 1=1
AND q.Q_CODE IN ('SHRM_MIAC_CNS', 'SHRM_MIAC_PNS_ODA', 'SHRM_MIAC_SOM')
AND aq.DATE_CREATE = (
       SELECT MAX(aq2.DATE_CREATE)
       FROM D_AGENT_QUESTIONARIES aq2
       JOIN D_QUESTIONARIES q2 ON q2.id = aq2.QUESTIONARY
       WHERE aq2.UNIT_ID = v.ID
         AND q2.Q_CODE IN ('SHRM_MIAC_CNS', 'SHRM_MIAC_PNS_ODA', 'SHRM_MIAC_SOM')
   )
AND v.ID = :REP_VISIT_ID
